export const SlideData = [
    {
      image:
        "../../img/Frame 1000002241.png"
    },
    {
      image:
        "../../img/Testist1.png"
    },
    {
      image:
        "../../img/Testi2.png"
    },
    {
      image:
        "../../img/Testist2.png"
    },
    {
      image:
        "../../img/Testi3.png"
    },
    {
      image:
        "../../img/Testist3.png"
    },
    {
      image:
        "../../img/Testi4.png"
    },
    {
      image:
        "../../img/Testist4.png"
    },
    {
      image:
        "../../img/Testi5.png"
    },
    {
      image:
        "../../img/Testist5.png"
    }
  ];
